djangoProject/djangoProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profiles/', include("tamilmatrimony.urls", namespace= "profiles")),
    url(r'^register/', "tamilmatrimony.views.register", name="register"),
    url(r'^login/',"tamilmatrimony.views.login_user",name= "login"),
    url(r'^logout/',"tamilmatrimony.views.logout_view",name= "logout"),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoProject/tamilmatrimony/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

urlpatterns = [

    url(r'^$', "tamilmatrimony.views.profile_list", name='list'),

    url(r'^search/$', "tamilmatrimony.views.profile_search_list", name='search1'),
    url(r'^search_by_id/$', "tamilmatrimony.views.profile_search_id", name='search2'),

    url(r'^create/$', "tamilmatrimony.views.profile_create", name='create'),
    url(r'^myprofile/$', "tamilmatrimony.views.my_profile", name='myprofile'),
    url(r'^all_profiles/$', "tamilmatrimony.views.profile_list_all", name='allprofiles'),

    url(r'^myprofile/edit/$', "tamilmatrimony.views.myprofile_update", name='myedit'),

    url(r'^(?P<slug>[\w.@+-]+)/$', "tamilmatrimony.views.profile_detail", name='detail'),
    url(r'^(?P<slug>[\w.@+-]+)/edit/$', "tamilmatrimony.views.profile_update", name='edit'),


    url(r'^(?P<slug>[\w.@+-]+)/delete/$', "tamilmatrimony.views.profile_delete"),

]

djangoProject/tamilmatrimony/models.py
from django.db import models
from django import forms
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import *
import string, random
from datetime import date
# Create your models here.

def upload_location(instance, filename):
    return "%s/%s" %(instance.slug, filename)


class profiles(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    #Basics & Lifestyle
    tmId = models.AutoField(primary_key=True)
    pId = models.CharField(max_length=10, default='TMG')
    slug = models.SlugField(unique=True)
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to= upload_location,null=True, blank=True,default="/media/default/pimage.png")
    thumbnail = ImageSpecField(

        source='image', processors=[SmartResize(600,600)],format='JPEG',
        options={'quality':70},

    )
    maritalStatus_choices = (
        ('single', 'Single'),
        ('married', 'Married'),
        ('divorced', 'Divorced'),
    )
    maritalStatus = models.CharField(max_length=25, choices=maritalStatus_choices, default='single')
    body_Type = models.CharField(max_length=15)
    height = models.CharField(max_length=15)
    weight = models.CharField(max_length=15)
    matrimonyProfileFor_choices = (
        ('son', 'Son'),
        ('daughter', 'Daughter'),
        ('brother', 'Brother'),
        ('sister', 'Sister'),
        ('self', 'Self'),
    )
    matrimonyProfileFor = models.CharField(max_length=25, choices=matrimonyProfileFor_choices, default='personal')
    drink = models.CharField(max_length=15)
    smoke = models.CharField(max_length=15)
    dateOfBirth = models.DateTimeField('Date of Birth/Time - Format : YYYY-MM-DD HH:MM', auto_now=False, auto_now_add=False,)



    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    age = models.IntegerField(default=0)
    motherTongue = models.CharField(max_length=50)
    gender_choices = (
        ('male', 'Male'),
        ('female', 'Female'),

    )
    gender = models.CharField(max_length=15, choices=gender_choices)
    blood_group = models.CharField(max_length=20,default="not specified")
    diet = models.CharField(max_length=20)

    #Religious / Social & Astro Background

    #timeOfBirth = models.TimeField( default= "00:00")
    religion_choices = (
        ('hindu','Hindu'),
        ('cristian','Cristian'),
        ('muslim','Muslim'),
        ('sikh','Sikh'),
        ('buddhist','Buddhist')
    )
    religion = models.CharField(max_length=50, choices=religion_choices)
    caste = models.CharField(max_length=50)
    sub_caste = models.CharField(max_length=25)
    #DOB
    placeOfBirth = models.CharField(max_length=30)
    rassi = models.CharField(max_length=30)

    #Education & Career

    education = models.CharField(max_length=50)
    education_detail = models.CharField(max_length=50)
    occupation_detail = models.CharField(max_length=100)
    annual_income = models.CharField(max_length=20, default="not specified")
    current_location = models.CharField(max_length=25)

    #Family Details

    father_occupation = models.CharField(max_length=50)
    mother_occupation = models.CharField(max_length=50)
    no_of_sisters = models.IntegerField(default=0)
    no_of_brother = models.IntegerField(default=0)




    #partner prefrences

    p_age_min = models.IntegerField(default=0)
    p_age_max = models.IntegerField(default=0)
    p_Marital_Status = models.CharField(max_length=10)
    p_Body_Type = models.CharField(max_length=25)
    p_Complexion = models.CharField(max_length=25)
    p_Height = models.CharField(max_length=25)

    p_Diet =  models.CharField(max_length=25)
    p_Manglik =  models.CharField(max_length=25)
    p_Religion =  models.CharField(max_length=25)
    p_Caste =  models.CharField(max_length=25)
    p_Mother_Tongue =  models.CharField(max_length=25)
    p_Education =  models.CharField(max_length=25)
    p_Country_Of_Residence =  models.CharField(max_length=25)
    p_State =  models.CharField(max_length=25)


    timestamp = models.DateTimeField(auto_now=False, auto_now_add= True)

    def __str__(self):
        return self.pId

    def get_absolute_url(self):
        return reverse("profiles:detail", kwargs={"slug":self.slug})
    class Meta:
        ordering =["-timestamp","-updated"]

def create_slug(instance, new_slug=None):
    slug= slugify(instance.name)
    if new_slug is not None:
        slug= new_slug
    qs = profiles.objects.filter(slug=slug).order_by("-tmId")
    exists = qs.exists()
    if exists:
        new_slug= "%s-%s" %(slug, qs.first().tmId)
        return create_slug(instance, new_slug = new_slug)
    return slug


def pre_save_post_signal_reciever(sender, instance, *args, **kwargs):


    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_signal_reciever, sender=profiles)

djangoProject/templates/base.html
<!DOCTYPE HTML>
<html>

<head>
<title>{% block head_title %}Tamil Matrimony Germany{% endblock head_title %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Marital Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href="/static/css/bootstrap-3.1.1.min.css" rel='stylesheet' type='text/css' />
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="/static/js/jquery.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<!-- Custom Theme files -->
<link href="/static/css/style.css" rel='stylesheet' type='text/css' />

<link href='http://fonts.googleapis.com/css?family=Oswald:300,400,700' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700' rel='stylesheet' type='text/css'>
<!----font-Awesome----->
<link href="/static/css/font-awesome.css" rel="stylesheet">
<!----font-Awesome----->
<script>
$(document).ready(function(){
    $(".dropdown").hover(            
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideDown("fast");
            $(this).toggleClass('open');        
        },
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideUp("fast");
            $(this).toggleClass('open');       
        }
    );
});
</script>
</head>
<body>
{% block header %}

{% endblock %}
<!-- ============================  Navigation Start =========================== -->
 <div class="navbar navbar-inverse-blue ">
    <!--<div class="navbar navbar-inverse-blue navbar-fixed-top">-->
      <div class="navbar-inner navbar-inner_1">
        <div class="container">
           <div class="navigation">
             <nav id="colorNav">
			   <ul>
				<li class="green">
					<a href="#" class="icon-home"></a>
					{% if user.is_authenticated %}
                    <ul >
					    <li><a href="{% url 'profiles:create' %}">Create Profile</a></li>
					    <li><a href="{% url 'logout' %}">Logout</a></li>
		              </ul>

                    {% else %}
                      <ul >
		                <li><a href="{%  url 'login' %}">Login</a></li>
					    <li><a href="{% url 'register' %}">Register</a></li>
		              </ul>

                {% endif %}
				</li>
			   </ul>
             </nav>
           </div>
            <a class="brand" href="{% url 'profiles:list' %}"><img src="/static/images/logo.png" alt="logo"></a>
           <div class="pull-right">
          	<nav class="navbar nav_bottom" role="navigation">
 
		 <!-- Brand and toggle get grouped for better mobile display -->
		  <div class="navbar-header nav_2">
		      <button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">Menu
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand" href="#"></a>
		   </div> 
		   <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-megadropdown-tabs" >
		        <ul class="nav navbar-nav nav_1">
		            <li><a href="{% url 'profiles:list' %}">Home</a></li>
		            <li><a href="#">About</a></li>
                    <li><a href="{% url 'profiles:allprofiles' %}">All Profiles</a></li>
                        <li class="dropdown">
		              <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Profile<span class="caret"></span></a>
		              <ul class="dropdown-menu" role="menu">
		                <li><a href="{% url 'profiles:myprofile' %}">View Profile</a></li>

		                <li><a href="{% url 'profiles:myedit' %}">Update Profile</a></li>

		              </ul>
		            </li>

					<li class="dropdown">
		              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Search<span class="caret"></span></a>
		              <ul class="dropdown-menu" role="menu">
		                <li><a href="{% url 'profiles:search1' %}">Advanced Search</a></li>

		                <li><a href="{% url 'profiles:search2' %}">Search By Profile ID</a></li>

		              </ul>
		            </li>
                {% if user.is_authenticated %}
                    <li class="dropdown">
		              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Welcome {{ user.username }}<span class="caret"></span></a>
		              <ul class="dropdown-menu" role="menu">
					    <li><a href="{% url 'profiles:create' %}">Create Profile</a></li>
					    <li><a href="{% url 'logout' %}">Logout</a></li>
		              </ul>
		            </li>
                    {% else %}
                     <li class="dropdown">
		              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Welcome Guest<span class="caret"></span></a>
		              <ul class="dropdown-menu" role="menu">
		                <li><a href="{%  url 'login' %}">Login</a></li>
					    <li><a href="{% url 'register' %}">Register</a></li>
		              </ul>
		            </li>

                {% endif %}


		        </ul>
		     </div><!-- /.navbar-collapse -->

		    </nav>
		   </div> <!-- end pull-right -->
          <div class="clearfix"> </div>
        </div> <!-- end container -->
      </div> <!-- end navbar-inner -->
    </div> <!-- end navbar-inverse-blue -->
<!-- ============================  Navigation End ============================ -->
{% block content %}
{% endblock content %}
{% block content1 %}
{% endblock content1 %}
{% block content2 %}
{% endblock content2 %}
{% block content3 %}
{% endblock content3 %}
{% block content4 %}
{% endblock content4 %}
<div class="footer">


<div class="container-fluid">
	<img src="/static/images/design.png" class="responsive" width="100%" height="auto">

    		<div class="copy">
		      <p>Copyright © 2016 Tamil Matrimony germany . All Rights Reserved  | Design by <a href="#">Nishant Tamilselvan</a> </p>
	        </div>
    	</div>
</div>
<!-- FlexSlider -->
<script defer src="/static/js/jquery.flexslider.js"></script>
<link rel="stylesheet" href="/static/css/flexslider.css" type="text/css" media="screen" />

<script>
// Can also be used with $(document).ready()
$(window).load(function() {
  $('.flexslider').flexslider({
    animation: "slide",
    controlNav: "thumbnails"
  });
});
</script>   
</body>

</html>

djangoProject/templates/index.html
{% extends "base.html" %}
{% load crop%}

{% block head_title %}{{ title }} | {{ block.super }} {% endblock head_title %}
{% block user_login_status %}{% endblock user_login_status %}
{% block header %}

<div class="container-fuild">
	<img src="/static/images/header.jpg" class="responsive" width="100%" height="auto">
	</div>
<div class="container-fuild">
	<img src="/static/images/design.png" class="responsive" width="100%" height="auto">
	</div>
{% endblock %}
{% block content1 %}

<div style="background: url('/static/images/banner.jpg')no-repeat center transparent ;-webkit-background-size: cover" class="jumbotron">
{% include "messages.html" %}
<div class="container">
    <div  class="banner_info">
      <h3>Millions of verified Members</h3>
      <a href="{% url 'profiles:create' %}" class="hvr-shutter-out-horizontal">Create your Profile</a>
    </div>
  </div>
    </div>

{% endblock content1 %}


{% block content2  %}
    <div class="grid_1">
      <div class="container">
      	<h1>Latest Profiles</h1>
       	<div class="heart-divider">
			<span class="grey-line"></span>
			<i class="fa fa-heart pink-heart"></i>
			<i class="fa fa-heart grey-heart"></i>
			<span class="grey-line"></span>
        </div>
        <ul id="flexiselDemo3">
            {% for foo in objectset %}
	      <li><div class="col_1"><a href="{{ foo.get_absolute_url }}">
			<img src="{{ foo.thumbnail.url}}" alt="" class="hover-animation image-zoom-in img-responsive"/>
             <div class="layer m_1 hidden-link hover-animation delay1 fade-in">
                <div class="center-middle"></div>
             </div>
             <h3><span class="m_3">Profile ID : {{ foo.pId }}<br>{{ foo.name }}</span><br>{{ foo.age }}, {{ foo.religion }}, {{ foo.education_detail }}<br>{{ foo.occupation_detail }}</h3></a></div>
          </li>
            {% endfor %}

	    </ul>
	    <script type="text/javascript">
		 $(window).load(function() {
			$("#flexiselDemo3").flexisel({
				visibleItems: 6,
				animationSpeed: 1000,
				autoPlay:false,
				autoPlaySpeed: 3000,
				pauseOnHover: true,
				enableResponsiveBreakpoints: true,
		    	responsiveBreakpoints: {
		    		portrait: {
		    			changePoint:480,
		    			visibleItems: 1
		    		},
		    		landscape: {
		    			changePoint:640,
		    			visibleItems: 2
		    		},
		    		tablet: {
		    			changePoint:768,
		    			visibleItems: 3
		    		}
		    	}
		    });

		});
	   </script>
	   <script type="text/javascript" src="/static/js/jquery.flexisel.js"></script>
    </div>
</div>
{% endblock content2 %}

{% block content3 %}


    <div class="grid_2">
	<div class="container">

		<h2>Advanced Profile Filters</h2>
       	<div class="heart-divider">
			<span class="grey-line"></span>
			<i class="fa fa-heart pink-heart"></i>
			<i class="fa fa-heart grey-heart"></i>
			<span class="grey-line"></span>
        </div>
        <div class="row_1">

	    <div class="col-md-6 ">

	        <div class="religion">
               <div class="religion_1-title">Religion :</div>
			   <a href="#" target="_blank" class="religion_1" title="Hindu Matrimonial" style="padding-left:0px !important;">Hindu</a>
			    <span>|</span><a href="#" target="_blank" class="religion_1" title="Muslim Matrimonial">Muslim</a>
			 	<span>|</span><a href="#" target="_blank" class="religion_1" title="Christian Matrimonial">Christian</a>
			 	<span>|</span><a href="#" target="_blank" class="religion_1" title="Sikh Matrimonial">Sikh</a>
			 	<span>|</span><a href="#" target="_blank" class="religion_1" title="Inter Religion Matrimonial">Inter Religion</a>
	        </div>
	        <div class="religion">
               <div class="religion_1-title">Country :</div>
			   <a href="#" target="_blank" class="religion_1" title="Hindu Matrimonial" style="padding-left:0px !important;">India</a>
			    <span>|</span><a href="#" target="_blank" class="religion_1" title="Muslim Matrimonial">Australia</a>
			 	<span>|</span><a href="#" target="_blank" class="religion_1" title="Christian Matrimonial">Russia</a>
			 	<span>|</span><a href="#" target="_blank" class="religion_1" title="Sikh Matrimonial">India</a>
			 	<span>|</span><a href="#" target="_blank" class="religion_1" title="Inter Religion Matrimonial">Kuwait</a>
			 	<span>|</span><a href="#" target="_blank" class="religion_1" title="Inter Religion Matrimonial">Uk</a>
			 	<span>|</span><a href="#" target="_blank" class="religion_1" title="Inter Religion Matrimonial">View All</a>
	        </div>

	     </div>
          <div class="col-md-6 ">



	        <div class="religion">
               <div class="religion_1-title">Caste :</div>
			   <a href="#" target="_blank" class="religion_1" title="Hindu Matrimonial" style="padding-left:0px !important;">Brahmin</a>
			    <span>|</span><a href="#" target="_blank" class="religion_1" title="Muslim Matrimonial">Kapu</a>
			 	<span>|</span><a href="#" target="_blank" class="religion_1" title="Christian Matrimonial">Kamma</a>
			 	<span>|</span><a href="#" target="_blank" class="religion_1" title="Sikh Matrimonial">Padmasali</a>
			 	<span>|</span><a href="#" target="_blank" class="religion_1" title="Inter Religion Matrimonial">Reddy</a>
			 	<span>|</span><a href="#" target="_blank" class="religion_1" title="Inter Religion Matrimonial">View All</a>
	        </div>
	        <div class="religion">
               <div class="religion_1-title">Regional :</div>
			   <a href="#" target="_blank" class="religion_1" title="Hindu Matrimonial" style="padding-left:0px !important;">Urdu</a>
			    <span>|</span><a href="#" target="_blank" class="religion_1" title="Muslim Matrimonial">Hindi</a>
			 	<span>|</span><a href="#" target="_blank" class="religion_1" title="Christian Matrimonial">Telugu</a>
			 	<span>|</span><a href="#" target="_blank" class="religion_1" title="Sikh Matrimonial">Marwadi</a>
			 	<span>|</span><a href="#" target="_blank" class="religion_1" title="Inter Religion Matrimonial">Oriya</a>
			 	<span>|</span><a href="#" target="_blank" class="religion_1" title="Inter Religion Matrimonial">View All</a>
	        </div>
	     </div>

	   </div>
	  </div>
    </div>


{% endblock content3 %}

djangoProject/templates/profiles.html
{% extends "base.html" %}

{% block head_title %}{{ title }} | {{ block.super }} {% endblock head_title %}

{% block content %}
    <div class="grid_1">
        <div class="container">
            <div class="breadcrumb1">
     <ul>
        <a href="{% url 'profiles:list' %}"><i class="fa fa-home home_1"></i></a>
        <span class="divider">&nbsp;|&nbsp;</span>
        <li class="current-page">All Profiles</li>
     </ul>
   </div>
            <h1>Latest Updated Profiles</h1>

    <hr>


        </div>
    </div>
{% endblock content %}

{% block content1 %}

<div class="grid_3">
  <div class="container">



 <!---728x90--->
   <div class="col-md-10 col-md-offset-1  members_box">



<div class="members_box2 col-md-4 col-md-offset-8" >
    <ul  class="pagination">
       {% if objectset.has_previous %}
           <li><a href="?page={{ objectset.previous_page_number }}">previous</a></li>
        {% endif %}
 	  <li class="active"><a href="#">Page {{ objectset.number }} of {{ objectset.paginator.num_pages }}</a></li>
       {% if objectset.has_next %}
            <li><a href="?page={{ objectset.next_page_number }}">next</a></li>
        {% endif %}

	</ul>

<div class="clearfix"> </div>
</div>







{% for foo in objectset %}
	   <div class="profile_top"><a href="{{ foo.get_absolute_url }}">
      <h2>{{ foo.pId }}</h2>
	    <div class="col-sm-3 profile_left-top">
	    	<img src="{{ foo.thumbnail.url }}" class="img-thumbnail" alt=""/>
	    </div>
	    <div class="col-sm-3">
	      <ul class="login_details1">
			  <li><span style="color: lightcoral;text-align: center ">{{ foo.name |upper }}</span></li>
              <li>Last Login : {{ foo.updated | timesince }} ago</li>
		  </ul>
	    </div>
	    <div class="col-sm-6">
	    	<table class="table_working_hours">
	        	<tbody>
	        		<tr class="opened_1">
						<td class="day_label1">Age / Height :</td>
						<td class="day_value">{{ foo.age }}, {{ foo.height }}</td>
					</tr>
				    <tr class="opened">
						<td class="day_label1">Last Login :</td>
						<td class="day_value">{{ foo.updated | timesince }} ago</td>
					</tr>
				    <tr class="opened">
						<td class="day_label1">Religion :</td>
						<td class="day_value">{{ foo.religion }}</td>
					</tr>
				    <tr class="opened">
						<td class="day_label1">Marital Status :</td>
						<td class="day_value">{{ foo.maritalStatus }}</td>
					</tr>
				    <tr class="opened">
						<td class="day_label1">Location :</td>
						<td class="day_value">{{ foo.current_location }}</td>
					</tr>
				    <tr class="closed">
						<td class="day_label1">Profile Created by :</td>
						<td class="day_value closed"><span>{{ foo.matrimonyProfileFor }}</span></td>
					</tr>
				    <tr class="closed">
						<td class="day_label1">Education :</td>
						<td class="day_value closed"><span>{{ foo.education_detail }}</span></td>
					</tr>
			    </tbody>
		   </table>
		   <div class="buttons">
			   <div class="vertical">Send Mail</div>
			   <div class="vertical">Shortlisted</div>
			   <div class="vertical">Send Interest</div>
		   </div>
	    </div>
	    <div class="clearfix"> </div>
    </a></div>

 {% endfor %}

   <div class="members_box2 ">
    <ul  class="pagination">
       {% if objectset.has_previous %}
           <li><a href="?page={{ objectset.previous_page_number }}">previous</a></li>
        {% endif %}
 	  <li class="active"><a href="#">Page {{ objectset.number }} of {{ objectset.paginator.num_pages }}</a></li>
       {% if objectset.has_next %}
            <li><a href="?page={{ objectset.next_page_number }}">next</a></li>
        {% endif %}

	</ul>

<div class="clearfix"> </div>
</div>

   <div class="clearfix"> </div>
  </div>

</div>
</div>
{% endblock content1 %}

djangoProject/templates/register.html
{% extends "base.html" %}
 {% load widget_tweaks %}
{% load crispy_forms_tags %}
{% load crop %}

{% block head_title %}{{ title }} | {{ block.super }} {% endblock head_title %}


{% block content %}




    <div class="grid_3">
  <div class="container">
   <div class="breadcrumb1">
     <ul>
        <a href="index-2.html"><i class="fa fa-home home_1"></i></a>
        <span class="divider">&nbsp;|&nbsp;</span>
        <li class="current-page">Register</li>
     </ul>
   </div>

{% include "messages.html" %}

   <div class="services">
   	  <div class="col-sm-6 login_left">


           <form action="" method="POST" enctype="multipart/form-data" role="form">{% csrf_token %}
		<legend>Create a Basic Profile</legend>




<div id="div_id_name" class="form-group"> <label for="id_name" class="control-label  requiredField">
                Name<span class="asteriskField">*</span> </label> <div class="controls "> <input class="textinput textInput form-control" id="id_name" maxlength="50" name="name" required="required" type="text"> </div> </div> <div id="div_id_gender" class="form-group"> <label for="id_gender" class="control-label  requiredField">
                Gender<span class="asteriskField">*</span> </label> <div class="controls "> <select required="required" class="select form-control" id="id_gender" name="gender">
<option value="" selected="selected">---------</option>
<option value="male">Male</option>
<option value="female">Female</option>
</select> </div> </div> <div id="div_id_dateOfBirth" class="form-group"> <label for="id_dateOfBirth" class="control-label  requiredField">
                Date of Birth/Time - Format : YYYY-MM-DD HH:MM<span class="asteriskField">*</span> </label> <div class="controls "> <input required="required" class="datetimeinput form-control" id="id_dateOfBirth" name="dateOfBirth" type="text"> </div> </div> <div id="div_id_maritalStatus" class="form-group"> <label for="id_maritalStatus" class="control-label  requiredField">
                MaritalStatus<span class="asteriskField">*</span> </label> <div class="controls "> <select required="required" class="select form-control" id="id_maritalStatus" name="maritalStatus">
<option value="single" selected="selected">Single</option>
<option value="married">Married</option>
<option value="divorced">Divorced</option>
</select> </div> </div> <div id="div_id_religion" class="form-group"> <label for="id_religion" class="control-label  requiredField">
                Religion<span class="asteriskField">*</span> </label> <div class="controls "> <select required="required" class="select form-control" id="id_religion" name="religion">
<option value="" selected="selected">---------</option>
<option value="hindu">Hindu</option>
<option value="cristian">Cristian</option>
<option value="muslim">Muslim</option>
<option value="sikh">Sikh</option>
<option value="buddhist">Buddhist</option>
</select> </div> </div> <div id="div_id_image" class="form-group"> <label for="id_image" class="control-label ">
                Image
            </label> <div class="controls "> <input required="required" id="id_image" name="image" type="file"> </div> </div>






			  <div class="form-actions">
			    <input type="submit" name="submit" value="Save and Continue" class="btn_1 submit">
			  </div>

	    </form>

</div>
	  </div>
	  <div class="col-sm-6">
	     <ul class="sharing">
			<li><a href="#" class="facebook" title="Facebook"><i class="fa fa-boxed fa-fw fa-facebook"></i> Share on Facebook</a></li>
		  	<li><a href="#" class="twitter" title="Twitter"><i class="fa fa-boxed fa-fw fa-twitter"></i> Tweet</a></li>
		  	<li><a href="#" class="google" title="Google"><i class="fa fa-boxed fa-fw fa-google-plus"></i> Share on Google+</a></li>
		  	<li><a href="#" class="linkedin" title="Linkedin"><i class="fa fa-boxed fa-fw fa-linkedin"></i> Share on LinkedIn</a></li>
		  	<li><a href="#" class="mail" title="Email"><i class="fa fa-boxed fa-fw fa-envelope-o"></i> E-mail</a></li>
		 </ul>
	  </div>
	  <div class="clearfix"> </div>
   </div>

  </div>
</div>







{% endblock content %}